import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { ClientCookiesProvider } from "@/components/providers/cookies-provider";
import { SessionProvider } from "next-auth/react";
import { NextAuthProvider } from "@/components/providers/nextauth-provider";
import { DashboardProvider } from "@/components/providers/dashboard-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <ClientCookiesProvider value={cookies().getAll()}>
        <NextAuthProvider>
          <DashboardProvider>
            <body className={cn(inter.className, "min-h-screen")}>
              <Toaster richColors />
              <div className="min-h-screen">{children}</div>
              <div className="footer h-10 w-full bg-primary flex items-center mt-5">
                <div className="w-[70%] mx-auto flex justify-center gap-4 text-white text-sm">
                  <span>2023</span>
                  <p className="text-sm">Todos los derechos reservados.</p>
                </div>
              </div>
            </body>
          </DashboardProvider>
        </NextAuthProvider>
      </ClientCookiesProvider>
    </html>
  );
}
